name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  cupertino_icons: ^1.0.8
  dio: ^5.5.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Analysis & Testing
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.3

flutter:
  uses-material-design: true